name:      MyBB Documentation
markdown:  redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "with_toc_data", "autolink"]
pygments:  true
highlighter: pygments
permalink: pretty
baseurl:   //docs.mybb.com
mainsiteurl: //www.mybb.com
