name: MyBB Documentation
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
permalink: pretty
baseurl: /docs.mybb.com # MUST BE REMOVED BEFORE SUBMITTING PULL REQUEST
mainsiteurl: https://mybb.com

remote_theme: mybb/mybb-website-theme

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

exclude: ["CNAME", "README.md", "CONTRIBUTING.md", "key_private.key", "key_public.pem"]
