name:      MyBB Documentation
markdown:  redcarpet
redcarpet:
  extensions: ["tables", "with_toc_data", "autolink"]
pygments:  true
permalink: pretty
baseurl:   http://mybb.github.io
mainsiteurl: http://mybb.github.io/mybb.com
